### PR TITLE
upgrade peter-evans/create-pull-request to v4.0.1

### PR DESCRIPTION
**Pull request by edenhaus**
Upgrade action to fix error

### CODE REVIEW

**Comment by edenhaus** [comment]
@ludeeus Normally the dependabot should update the actions, but I have not enough rights to check, why it didn't work...

**Comment by ludeeus** [comment]
It did not work because I closed the PR.
https://github.com/ludeeus/container/pull/265

**Comment by edenhaus** [comment]
So you don't want to upgrade?

**Comment by ludeeus** [comment]
Im not sure I still want to use it, still looking at options.
If Im going to continue with it, it needs to be updated.

**Comment by edenhaus** [comment]
ah okay, I will close this PR

**Pull request closed without merging**
