### PR TITLE
Fix for issue #78

### PR DESCRIPTION
**Pull request by xannor**
Changed find arguments to only match custom_components under a subfolder of /workspaces to ignore non component projects

### CODE REVIEW

**Comment by xannor** [comment]
How do you get it to re-run checks, the things that failed are outside of my control?

**Review by ludeeus — CHANGES_REQUESTED** [review]
This will not work for containers/repositories that does not have a custom_components directory

**Comment by xannor** [comment]
Didn't realize that... If it checked the container type first and only did it for the integration type would that work?

**Comment by ludeeus** [comment]
TBH you should do that separately, with a separate repo and a separate devcontainer

**Comment by xannor** [comment]
I do have the lib as a separate repo, but how do you make and test changes in the lib if is in a separate container? I realize this is sidetracking the merge, but it feels like, by design, this is not something that is going to get changed, so I am trying to figure out what is the correct approach to properly develop and debug a custom component that depends on a custom library. Pushing every small change to pipy before verifying it works feels wrong, or am I misunderstanding something? Thanks for any info and I guess this and the associated issue can be closed.

**Comment by ludeeus** [comment]
What I do (and I know from talking to many others) is that we develop libraries completely separate as standalone sets of features that could be used outside a custom integration, if it can't then there is no use in even using a lib for that logic.

If I really want to test a branch/commit in my integration before pushing it to pypi, that can be done like this in the manifest file:
```json
{
  "requirements": ["git+https://github.com/issacg/pycoolmaster.git@except_connect#pycoolmaster==0.2.2"]
}
```
from <https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing>

**Comment by xannor** [comment]
Ok, thank you for the pointers, I'm going to close this and the related issue.

**Pull request closed without merging**
